# Generated by Django 3.1.6 on 2021-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210209_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.FileField(default='pstatic/reviewimg/no-img.jpg', upload_to='static/reviewimg'),
        ),
    ]
