# Generated by Django 3.1.6 on 2021-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(default='static/reviewimg/no-img.jpg', upload_to='static/reviewimg'),
        ),
    ]
